### PR TITLE
Add `contentProperties` option

### PR DESCRIPTION
**Pull request by svetlanapuro**
Address #15

### CODE REVIEW

**Comment by wooorm** [comment]
Super nice, awesome Svetlana! ✨

I do have a hunch that our tooling will change some of the code-style, namely, wrap the line.

Can you try `npm install` locally, to install dependencies, and then do `npm test`? That should make sure that everything is formatted, checked, and tested locally.

If that doesn’t change anything, it’s perfect, and ready to go!

**Comment by iloveip** [comment]
Thank you for your help) I pushed an update.

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Thanks, released!

In the future, it’s a good idea to add [docs](https://github.com/remarkjs/remark-external-links/commit/fec1378bcda3e9e3fc364737bd4b7342187f8d33) and [tests](https://github.com/remarkjs/remark-external-links/commit/133430b4ea957ab78e1f2d91ab9e784457f627cf) to new features.

Congrats on & thanks for your contribution!

**Comment by iloveip** [comment]
Ok, thank you very much 🙏

**Pull request merged**
