### PR TITLE
Update for changes in remark

### PR DESCRIPTION
**Pull request by fand**
ref. #1 

This PR fixes API changes introduced by latest version of remark.

## Changes
- Update remark, remark-html in `devDependencies`
- Fixed the order of params
- Fixed tests with async/await for promises returned by `.process()`
- Update Node.js on Travis CI to support async/await

### CODE REVIEW

**Comment by h-michael** [comment]
@xuopled 
Could you review and merge this PR?

**Comment by xuopled** [comment]
Thank you @h-michael for your work

**Comment by xuopled** [comment]
I published v2.0.0

**Comment by xuopled** [comment]
You were right to relaunch me. I completely missed the PR

**Pull request merged**
